@echo off
echo Activating virtual environment...
call .venv\Scripts\activate.bat

echo Installing dependencies...
pip install -r backend/requirements.txt

echo Building frontend...
npm run build

echo Starting backend...
uvicorn backend.main:app --host 0.0.0.0 --port 8001